https://developers.google.com/maps/documentation/javascript/directions#DraggableDirections
http://jsfiddle.net/fLogwsff/132/
http://jsfiddle.net/u9no8te4/2917/
https://stackoverflow.com/questions/5959788/google-maps-api-v3-how-show-the-direction-from-a-point-a-to-point-b-blue-line
https://www.google.co.id/search?rlz=1C1CHBF_enID790ID790&q=maps+api+directions+example&sa=X&ved=0ahUKEwjF4_CBg8jcAhXLpY8KHQsRAXMQ1QIIkwEoAQ&biw=1440&bih=794
https://developers.google.com/maps/documentation/javascript/examples/directions-draggable